// lib/runtime/report.ts
//
// Pure formatter that turns a PipelineResult into a human-readable Markdown
// report. Used by scripts/run-pipeline.ts to leave a self-contained record on
// disk for every run (success or blocked) — the "final result" companion to
// the developer's generated code.
//
// Design notes:
//   - Pure: same input → same output. Only the supplied `now` clock is
//     externally provided; default is new Date(), but tests inject a fixed one.
//   - Robust to partial results: a pipeline blocked at validation has no
//     developer/qa/security outputs; the formatter renders only the sections
//     it has data for and clearly notes which steps were skipped.
//   - GitHub-flavoured Markdown (tables + fenced code blocks).
//   - Includes the FULL JSON of every captured agent output so the report is
//     lossless and self-contained — a downstream consumer can rebuild the
//     PipelineResult from the report alone.

import type { PipelineResult } from "./pipeline.ts";
import type {
  CEOOutput,
  CTOOutput,
  DeveloperOutput,
  EMOutput,
  QAOutput,
  SecurityOutput,
} from "./types.ts";

export interface FormatReportOptions {
  /** Inject a clock for testability. Default: new Date(). */
  now?: Date;
  /** Trailing footer line. Default: tool credit. */
  footer?: string;
}

export function formatReportMarkdown(
  result: PipelineResult,
  options: FormatReportOptions = {},
): string {
  const now = options.now ?? new Date();
  const footer = options.footer ?? "_Generated by the AI Organisation pipeline runner._";

  const totalMs = result.steps.reduce((acc, s) => acc + s.durationMs, 0);
  const sections: string[] = [];

  // ---------- Header ----------
  sections.push(
    [
      `# Pipeline run report`,
      ``,
      `- **Idea:** ${oneline(result.idea) || "_(empty)_"}`,
      `- **Decision:** ${decisionLine(result.decision)}`,
      `- **Timestamp:** ${now.toISOString()}`,
      `- **Total time:** ${totalMs} ms across ${result.steps.length} step(s)`,
      result.blockReason ? `- **Block reason:** ${escapeInline(result.blockReason)}` : null,
    ]
      .filter((l): l is string => l != null)
      .join("\n"),
  );

  // ---------- Steps timeline ----------
  if (result.steps.length > 0) {
    const rows = result.steps.map(
      (s, i) =>
        `| ${i + 1} | \`${s.name}\` | ${stepStatusBadge(s.status)} | ${s.durationMs} ms | ${escapeCell(s.details ?? "")} |`,
    );
    sections.push(
      [
        `## Steps`,
        ``,
        `| # | Step | Status | Duration | Notes |`,
        `|---|------|--------|----------|-------|`,
        ...rows,
      ].join("\n"),
    );
  }

  // ---------- Validation ----------
  sections.push(
    [
      `## Validation`,
      ``,
      result.validation.valid
        ? `Valid \u2014 ${result.outputs.em ? `${result.outputs.em.features.length} feature(s), ${result.outputs.em.tasks.length} task(s)` : `(no EM output)`}`
        : `Invalid \u2014 ${result.validation.errors.length} error(s)`,
      ...(result.validation.valid
        ? []
        : [
            ``,
            ...result.validation.errors.slice(0, 10).map((e) => `- \`${e.path}\` [${e.rule}]: ${escapeInline(e.message)}`),
            result.validation.errors.length > 10 ? `- _...and ${result.validation.errors.length - 10} more_` : null,
          ]),
    ]
      .filter((l): l is string => l != null)
      .join("\n"),
  );

  // ---------- Selected task ----------
  if (result.selectedTask && result.selectedFeature) {
    sections.push(
      [
        `## Selected task`,
        ``,
        `- **Task:** \`${result.selectedTask.id}\` \u2014 ${escapeInline(result.selectedTask.description)}`,
        `- **Assignee:** ${result.selectedTask.assignedTo}`,
        `- **Estimate:** ${result.selectedTask.estimatedHours} h`,
        `- **Feature:** \`${result.selectedFeature.id}\` \u2014 ${escapeInline(result.selectedFeature.name)}`,
      ].join("\n"),
    );
  } else {
    sections.push([`## Selected task`, ``, `_No task was selected this run._`].join("\n"));
  }

  // ---------- Files written ----------
  if (result.filesWritten.length > 0) {
    const rows = result.filesWritten.map(
      (f) => `| \`${escapeCell(f.declaredPath)}\` | ${f.bytes} | \`${escapeCell(f.absolutePath)}\` |`,
    );
    sections.push(
      [
        `## Files written`,
        ``,
        `${result.filesWritten.length} file(s), ${sumBytes(result.filesWritten)} bytes total.`,
        ``,
        `| Path | Bytes | Absolute |`,
        `|------|-------|----------|`,
        ...rows,
      ].join("\n"),
    );
  } else {
    sections.push([`## Files written`, ``, `_No files were written this run._`].join("\n"));
  }

  // ---------- Per-agent sections ----------
  sections.push(`## Agent outputs`);

  if (result.outputs.ceo) sections.push(renderCEO(result.outputs.ceo));
  else sections.push(`### CEO\n\n_Did not run._`);

  if (result.outputs.cto) sections.push(renderCTO(result.outputs.cto));
  else sections.push(`### CTO\n\n_Did not run._`);

  if (result.outputs.em) sections.push(renderEM(result.outputs.em));
  else sections.push(`### Engineering Manager\n\n_Did not run._`);

  if (result.outputs.developer) sections.push(renderDeveloper(result.outputs.developer));
  else sections.push(`### Developer\n\n_Did not run._`);

  if (result.outputs.qa) sections.push(renderQA(result.outputs.qa));
  else sections.push(`### QA\n\n_Did not run._`);

  if (result.outputs.security) sections.push(renderSecurity(result.outputs.security));
  else sections.push(`### Cybersecurity\n\n_Did not run._`);

  // ---------- Footer ----------
  sections.push(`---\n\n${footer}`);

  return sections.join("\n\n") + "\n";
}

// ---------- per-agent renderers ----------

function renderCEO(o: CEOOutput): string {
  const okrs = o.okrs.length > 0 ? o.okrs.map((k) => `- ${escapeInline(k)}`).join("\n") : `_(none)_`;
  const priorities =
    o.priorities.length > 0 ? o.priorities.map((p) => `- ${escapeInline(p)}`).join("\n") : `_(none)_`;
  return [
    `### CEO`,
    ``,
    `**Mission:** ${escapeInline(o.mission)}`,
    ``,
    `**OKRs:**`,
    okrs,
    ``,
    `**Priorities:**`,
    priorities,
    ``,
    `**Delegation:**`,
    `- **CTO:** ${escapeInline(o.delegation.cto) || "_(empty)_"}`,
    `- **CMO:** ${escapeInline(o.delegation.cmo) || "_(empty)_"}`,
    `- **CFO:** ${escapeInline(o.delegation.cfo) || "_(empty)_"}`,
    `- **CPO:** ${escapeInline(o.delegation.cpo) || "_(empty)_"}`,
    ``,
    detailsBlock("Full CEO output (JSON)", o),
  ].join("\n");
}

function renderCTO(o: CTOOutput): string {
  const apis =
    o.apiContracts.length > 0
      ? o.apiContracts.map((a) => `- \`${a.method} ${a.endpoint}\` \u2014 ${escapeInline(a.description)}`).join("\n")
      : `_(none)_`;
  const tables =
    o.databaseSchema.length > 0
      ? o.databaseSchema
          .map((t) => `- **\`${t.table}\`**\n${t.fields.map((f) => `    - \`${escapeInline(f)}\``).join("\n")}`)
          .join("\n")
      : `_(none)_`;
  const risks = o.risks.length > 0 ? o.risks.map((r) => `- ${escapeInline(r)}`).join("\n") : `_(none)_`;
  return [
    `### CTO`,
    ``,
    `**Architecture:**`,
    `- Frontend: ${escapeInline(o.architecture.frontend)}`,
    `- Backend: ${escapeInline(o.architecture.backend)}`,
    `- Database: ${escapeInline(o.architecture.database)}`,
    `- Infrastructure: ${escapeInline(o.architecture.infrastructure)}`,
    ``,
    `**API contracts:**`,
    apis,
    ``,
    `**Database schema:**`,
    tables,
    ``,
    `**Risks:**`,
    risks,
    ``,
    detailsBlock("Full CTO output (JSON)", o),
  ].join("\n");
}

function renderEM(o: EMOutput): string {
  const features = o.features
    .map((f) => `- \`${f.id}\` (${f.priority}) \u2014 ${escapeInline(f.name)}`)
    .join("\n");
  const tasks = o.tasks
    .map(
      (t) =>
        `- \`${t.id}\` \u2192 \`${t.featureId}\` \u00b7 ${t.assignedTo} \u00b7 ${t.estimatedHours}h \u2014 ${escapeInline(t.description)}`,
    )
    .join("\n");
  return [
    `### Engineering Manager`,
    ``,
    `**Features (${o.features.length}):**`,
    features || `_(none)_`,
    ``,
    `**Tasks (${o.tasks.length}):**`,
    tasks || `_(none)_`,
    ``,
    detailsBlock("Full Engineering Manager output (JSON)", o),
  ].join("\n");
}

function renderDeveloper(o: DeveloperOutput): string {
  const filesList =
    o.files.length > 0 ? o.files.map((f) => `- \`${escapeInline(f.path)}\` (${f.content.length} bytes)`).join("\n") : `_(none)_`;
  const tests =
    o.tests.length > 0 ? o.tests.map((t) => `- ${escapeInline(t.description)}`).join("\n") : `_(none)_`;
  const notes = o.notes.length > 0 ? o.notes.map((n) => `- ${escapeInline(n)}`).join("\n") : `_(none)_`;
  return [
    `### Developer (executed \`${o.taskId}\`)`,
    ``,
    `**Implementation plan:**`,
    ``,
    `> ${escapeInline(o.implementationPlan)}`,
    ``,
    `**Files produced (${o.files.length}):**`,
    filesList,
    ``,
    `**Tests (${o.tests.length}):**`,
    tests,
    ``,
    `**Notes (${o.notes.length}):**`,
    notes,
    ``,
    detailsBlock("Full Developer output (JSON, includes file contents)", o),
  ].join("\n");
}

function renderQA(o: QAOutput): string {
  const passed = o.results.filter((r) => r.status === "pass").length;
  const failed = o.results.filter((r) => r.status === "fail").length;
  const decisionBadge = o.decision === "PASS" ? "\u2705 PASS" : o.decision === "CONDITIONAL" ? "\u26a0\ufe0f CONDITIONAL" : "\u274c FAIL";
  const bugs =
    o.bugs.length > 0
      ? o.bugs
          .map(
            (b) =>
              `- ${escapeInline(b.description)} (expected: ${escapeInline(b.expected)}, actual: ${escapeInline(b.actual)})`,
          )
          .join("\n")
      : `_(none)_`;
  return [
    `### QA`,
    ``,
    `- **Decision:** ${decisionBadge}`,
    `- **Test plan:** ${o.testPlan.length} item(s)`,
    `- **Results:** ${passed} pass, ${failed} fail`,
    `- **Bugs:** ${o.bugs.length}`,
    ``,
    `**Bugs:**`,
    bugs,
    ``,
    detailsBlock("Full QA output (JSON)", o),
  ].join("\n");
}

function renderSecurity(o: SecurityOutput): string {
  const decisionBadge = o.decision === "GO" ? "\u2705 GO" : "\u274c NO_GO";
  const vulns =
    o.vulnerabilities.length > 0
      ? o.vulnerabilities
          .map((v) => `- ${severityBadge(v.severity)} \u2014 ${escapeInline(v.description)}\n    - **Recommendation:** ${escapeInline(v.recommendation)}`)
          .join("\n")
      : `_(none)_`;
  const fixes = o.requiredFixes.length > 0 ? o.requiredFixes.map((r) => `- ${escapeInline(r)}`).join("\n") : `_(none)_`;
  return [
    `### Cybersecurity`,
    ``,
    `- **Decision:** ${decisionBadge}`,
    `- **Summary:** ${escapeInline(o.summary)}`,
    `- **Prompt-injection risk:** ${escapeInline(o.promptInjectionRisk)}`,
    ``,
    `**Vulnerabilities (${o.vulnerabilities.length}):**`,
    vulns,
    ``,
    `**Required fixes (${o.requiredFixes.length}):**`,
    fixes,
    ``,
    detailsBlock("Full Cybersecurity output (JSON)", o),
  ].join("\n");
}

// ---------- helpers ----------

function decisionLine(d: PipelineResult["decision"]): string {
  switch (d) {
    case "WROTE_FILES":
      return `\u2705 \`${d}\``;
    case "GATE_BLOCKED_QA":
    case "GATE_BLOCKED_SECURITY":
    case "VALIDATION_FAILED":
    case "NO_TASKS":
      return `\u26a0\ufe0f \`${d}\``;
    case "RUNTIME_ERROR":
      return `\u274c \`${d}\``;
  }
}

function stepStatusBadge(s: "ok" | "blocked" | "skipped"): string {
  switch (s) {
    case "ok":
      return "\u2705 ok";
    case "blocked":
      return "\u274c blocked";
    case "skipped":
      return "\u26aa skipped";
  }
}

function severityBadge(s: "critical" | "high" | "medium" | "low"): string {
  switch (s) {
    case "critical":
      return "\ud83d\udfe5 critical";
    case "high":
      return "\ud83d\udfe7 high";
    case "medium":
      return "\ud83d\udfe1 medium";
    case "low":
      return "\ud83d\udfe2 low";
  }
}

function detailsBlock(title: string, body: unknown): string {
  return `<details>\n<summary>${escapeInline(title)}</summary>\n\n\`\`\`json\n${JSON.stringify(body, null, 2)}\n\`\`\`\n\n</details>`;
}

function oneline(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

function escapeInline(s: string): string {
  // For inline text in lists / paragraphs: collapse whitespace, escape pipes
  // (table cells use a separate helper).
  return oneline(s).replace(/\|/g, "\\|");
}

function escapeCell(s: string): string {
  return oneline(s).replace(/\|/g, "\\|").replace(/`/g, "'");
}

function sumBytes(files: PipelineResult["filesWritten"]): number {
  let total = 0;
  for (const f of files) total += f.bytes;
  return total;
}
