// lib/runtime/report-pdf.ts
//
// Pure formatter that turns a PipelineResult into a self-contained, print-
// ready PDF report — the polished companion to formatReportMarkdown.
//
// Design notes:
//   - Pure: same input → same output. The wall clock is injected via `now`
//     for deterministic tests.
//   - Robust to partial results: a pipeline blocked at validation has no
//     developer/qa/security outputs; the renderer flags each missing agent
//     section as "Did not run." rather than throwing.
//   - Layout: a cover page (idea + colored decision badge + metadata),
//     followed by Steps / Validation / Selected task / Files written tables,
//     followed by per-agent sections — each starting on a new page so the
//     report is easy to navigate. Footers carry "Page X of N · timestamp".
//   - Built on PDFKit's built-in Helvetica + Courier families, so no font
//     files ship with the repo.
//   - Compression is on by default; tests opt out with `compress: false` so
//     the resulting buffer is text-searchable.
//
// Production wiring lives in scripts/run-pipeline.ts, which writes the PDF
// alongside REPORT.md (success → generated/{taskId}/REPORT.pdf, blocked →
// generated/_runs/{ts}/REPORT.pdf). PDF generation failures are non-fatal
// for the pipeline run; they surface on stderr.

import PDFDocument from "pdfkit";

import type { PipelineResult } from "./pipeline.ts";
import type {
  CEOOutput,
  CTOOutput,
  DeveloperOutput,
  EMOutput,
  QAOutput,
  SecurityOutput,
} from "./types.ts";

export interface FormatReportPdfOptions {
  /** Inject a clock for testability. Default: new Date(). */
  now?: Date;
  /** Document title (cover + PDF metadata). Default: "Pipeline Run Report". */
  title?: string;
  /** Footer line shown on every page. Default: tool credit. */
  footer?: string;
  /**
   * PDF stream compression. Default true.
   * Tests pass `false` so the raw buffer is text-searchable for assertions.
   */
  compress?: boolean;
}

// ---------- visual constants ----------

const COLORS = {
  primary: "#4f46e5",
  primaryDark: "#3730a3",
  text: "#0f172a",
  textMuted: "#475569",
  border: "#e2e8f0",
  panel: "#f8fafc",
  panelStrong: "#eef2ff",
  code: "#f1f5f9",
  ok: "#16a34a",
  warn: "#d97706",
  error: "#dc2626",
  white: "#ffffff",
  // Severity palette (mirrors Markdown badges)
  sevCritical: "#b91c1c",
  sevHigh: "#ea580c",
  sevMedium: "#ca8a04",
  sevLow: "#16a34a",
} as const;

const PAGE = {
  // A4 in PDF points (72pt = 1 in)
  width: 595.28,
  height: 841.89,
  margin: { top: 64, right: 56, bottom: 64, left: 56 },
} as const;

const CONTENT_WIDTH = PAGE.width - PAGE.margin.left - PAGE.margin.right;
const CONTENT_RIGHT = PAGE.margin.left + CONTENT_WIDTH;
const PAGE_BOTTOM = PAGE.height - PAGE.margin.bottom;

// ---------- public API ----------

export function formatReportPdf(
  result: PipelineResult,
  options: FormatReportPdfOptions = {},
): Promise<Buffer> {
  const now = options.now ?? new Date();
  const title = options.title ?? "Pipeline Run Report";
  const footer = options.footer ?? "Generated by the AI Organisation pipeline runner.";
  const compress = options.compress ?? true;

  return new Promise((resolvePdf, rejectPdf) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      size: [PAGE.width, PAGE.height],
      margins: PAGE.margin,
      bufferPages: true,
      compress,
      info: {
        Title: title,
        Subject: `Pipeline run: ${oneline(result.idea).slice(0, 240)}`,
        Producer: "AI Organisation",
        Creator: "AI Organisation pipeline runner",
        CreationDate: now,
      },
    });

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolvePdf(Buffer.concat(chunks)));
    doc.on("error", rejectPdf);

    try {
      drawCoverPage(doc, result, title, now);

      // Run summary on the next page.
      doc.addPage();
      drawSectionHeading(doc, "Steps");
      drawStepsTable(doc, result);

      drawSectionHeading(doc, "Validation");
      drawValidationBlock(doc, result);

      drawSectionHeading(doc, "Selected task");
      drawSelectedTaskBlock(doc, result);

      drawSectionHeading(doc, "Files written");
      drawFilesWrittenTable(doc, result);

      // Each agent gets its own page so the report is easy to skim.
      drawAgentPage(doc, "CEO", result.outputs.ceo, renderCEO);
      drawAgentPage(doc, "CTO", result.outputs.cto, renderCTO);
      drawAgentPage(doc, "Engineering Manager", result.outputs.em, renderEM);
      drawAgentPage(doc, "Developer", result.outputs.developer, renderDeveloper);
      drawAgentPage(doc, "QA", result.outputs.qa, renderQA);
      drawAgentPage(doc, "Cybersecurity", result.outputs.security, renderSecurity);

      addFootersToAllPages(doc, footer, now);
      doc.end();
    } catch (e) {
      rejectPdf(e);
    }
  });
}

// ---------- cover page ----------

function drawCoverPage(doc: PDFKit.PDFDocument, r: PipelineResult, title: string, now: Date): void {
  // Indigo header band
  doc.save();
  doc.fillColor(COLORS.primary);
  doc.rect(0, 0, PAGE.width, 110).fill();
  doc.restore();

  // Wordmark
  doc.save();
  doc.fillColor(COLORS.white).font("Helvetica-Bold").fontSize(11);
  doc.text("AI ORGANISATION", PAGE.margin.left, 32, { characterSpacing: 2 });
  doc.font("Helvetica").fontSize(20);
  doc.text(title, PAGE.margin.left, 50, { width: CONTENT_WIDTH });
  doc.restore();

  // Reset cursor below band
  doc.x = PAGE.margin.left;
  doc.y = 150;

  // Idea
  doc.font("Helvetica").fontSize(10).fillColor(COLORS.textMuted);
  doc.text("IDEA", { characterSpacing: 1.5 });
  doc.moveDown(0.3);
  doc.font("Helvetica-Bold").fontSize(20).fillColor(COLORS.text);
  const ideaText = oneline(r.idea) || "(empty)";
  doc.text(ideaText, { width: CONTENT_WIDTH, lineGap: 4 });

  doc.moveDown(1.2);

  // Decision badge
  drawDecisionBadge(doc, r.decision);

  // Block reason (if any)
  if (r.blockReason) {
    doc.moveDown(0.6);
    doc.font("Helvetica").fontSize(10).fillColor(COLORS.textMuted);
    doc.text("BLOCK REASON", { characterSpacing: 1.5 });
    doc.moveDown(0.2);
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.text);
    doc.text(oneline(r.blockReason), { width: CONTENT_WIDTH });
  }

  doc.moveDown(1.2);

  // Metadata panel
  const totalMs = r.steps.reduce((acc, s) => acc + s.durationMs, 0);
  const filesBytes = r.filesWritten.reduce((acc, f) => acc + f.bytes, 0);
  const meta: Array<[string, string]> = [
    ["Timestamp", now.toISOString()],
    ["Total time", `${totalMs.toLocaleString()} ms across ${r.steps.length} step(s)`],
    [
      "Validation",
      r.validation.valid
        ? `valid · ${r.outputs.em ? `${r.outputs.em.features.length} feature(s), ${r.outputs.em.tasks.length} task(s)` : "no EM output"}`
        : `invalid · ${r.validation.errors.length} error(s)`,
    ],
    [
      "Selected task",
      r.selectedTask && r.selectedFeature
        ? `${r.selectedTask.id} (${r.selectedTask.assignedTo}, ${r.selectedTask.estimatedHours}h) -> ${r.selectedFeature.id}`
        : "—",
    ],
    ["QA", r.outputs.qa ? r.outputs.qa.decision : "did not run"],
    ["Cybersecurity", r.outputs.security ? r.outputs.security.decision : "did not run"],
    [
      "Files written",
      r.filesWritten.length > 0
        ? `${r.filesWritten.length} file(s), ${filesBytes.toLocaleString()} bytes`
        : "none",
    ],
  ];
  drawMetadataPanel(doc, meta);

  // Footer note (left-aligned, just above the bottom band of cover)
  doc.fontSize(9).fillColor(COLORS.textMuted).font("Helvetica-Oblique");
  doc.text(
    "This report captures the full agent chain (CEO -> CTO -> Engineering Manager -> Developer -> QA -> Cybersecurity). Each agent's complete output is included in the per-agent sections.",
    PAGE.margin.left,
    PAGE_BOTTOM - 50,
    { width: CONTENT_WIDTH, align: "left" },
  );

  // Bottom indigo accent line
  doc.save();
  doc.fillColor(COLORS.primary);
  doc.rect(0, PAGE.height - 6, PAGE.width, 6).fill();
  doc.restore();
}

function drawDecisionBadge(doc: PDFKit.PDFDocument, decision: PipelineResult["decision"]): void {
  const { color, label } = decisionVisual(decision);
  const text = `Decision: ${label}`;
  doc.font("Helvetica-Bold").fontSize(12);
  const textWidth = doc.widthOfString(text);
  const padX = 14;
  const padY = 7;
  const w = textWidth + padX * 2;
  const h = 28;
  const x = PAGE.margin.left;
  const y = doc.y;

  doc.save();
  doc.fillColor(color);
  drawRoundedRect(doc, x, y, w, h, 4).fill();
  doc.restore();

  doc.save();
  doc.fillColor(COLORS.white).font("Helvetica-Bold").fontSize(12);
  doc.text(text, x + padX, y + padY);
  doc.restore();

  doc.x = PAGE.margin.left;
  doc.y = y + h;
}

function drawMetadataPanel(doc: PDFKit.PDFDocument, rows: ReadonlyArray<readonly [string, string]>): void {
  const rowHeight = 22;
  const labelWidth = 130;
  const valueX = PAGE.margin.left + 16 + labelWidth;
  const valueWidth = CONTENT_WIDTH - 32 - labelWidth;
  const panelHeight = rowHeight * rows.length + 20;
  const x = PAGE.margin.left;
  const y = doc.y;

  doc.save();
  doc.fillColor(COLORS.panel);
  drawRoundedRect(doc, x, y, CONTENT_WIDTH, panelHeight, 6).fill();
  doc.restore();

  let cursorY = y + 12;
  for (const [label, value] of rows) {
    doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.textMuted);
    doc.text(label.toUpperCase(), x + 16, cursorY, { width: labelWidth, characterSpacing: 1 });
    doc.font("Helvetica").fontSize(11).fillColor(COLORS.text);
    doc.text(value, valueX, cursorY - 1, { width: valueWidth, ellipsis: true, height: rowHeight });
    cursorY += rowHeight;
  }

  doc.x = PAGE.margin.left;
  doc.y = y + panelHeight + 10;
}

// ---------- run-summary section helpers ----------

function drawSectionHeading(doc: PDFKit.PDFDocument, label: string): void {
  ensureSpace(doc, 50);
  doc.moveDown(0.6);
  const y = doc.y;
  // Left accent stripe
  doc.save();
  doc.fillColor(COLORS.primary);
  doc.rect(PAGE.margin.left, y + 2, 3, 18).fill();
  doc.restore();
  doc.font("Helvetica-Bold").fontSize(15).fillColor(COLORS.text);
  doc.text(label, PAGE.margin.left + 12, y, { width: CONTENT_WIDTH - 12 });
  doc.x = PAGE.margin.left;
  doc.moveDown(0.4);
}

function drawStepsTable(doc: PDFKit.PDFDocument, r: PipelineResult): void {
  if (r.steps.length === 0) {
    drawMutedLine(doc, "(no steps recorded)");
    return;
  }
  const cols = [
    { x: PAGE.margin.left, width: 24, align: "right" as const },
    { x: PAGE.margin.left + 24, width: 138, align: "left" as const },
    { x: PAGE.margin.left + 162, width: 80, align: "left" as const },
    { x: PAGE.margin.left + 242, width: 70, align: "right" as const },
    { x: PAGE.margin.left + 312, width: CONTENT_WIDTH - 312, align: "left" as const },
  ];
  drawTableHeader(doc, ["#", "Step", "Status", "Duration", "Notes"], cols);
  for (let i = 0; i < r.steps.length; i++) {
    const s = r.steps[i];
    const statusVisual = stepStatusVisual(s.status);
    drawTableRow(
      doc,
      [
        String(i + 1),
        s.name,
        statusVisual.label,
        `${s.durationMs.toLocaleString()} ms`,
        oneline(s.details ?? ""),
      ],
      cols,
      {
        striped: i % 2 === 1,
        cellColors: [undefined, undefined, statusVisual.color, undefined, undefined],
        cellFonts: [undefined, "code", undefined, undefined, undefined],
      },
    );
  }
  doc.moveDown(0.3);
}

function drawValidationBlock(doc: PDFKit.PDFDocument, r: PipelineResult): void {
  if (r.validation.valid) {
    const features = r.outputs.em?.features.length ?? 0;
    const tasks = r.outputs.em?.tasks.length ?? 0;
    drawBodyLine(doc, `Valid — ${features} feature(s), ${tasks} task(s).`);
    return;
  }
  drawBodyLine(doc, `Invalid — ${r.validation.errors.length} error(s).`);
  const sample = r.validation.errors.slice(0, 8);
  for (const e of sample) {
    drawBulletLine(doc, `[${e.rule}] ${e.path}: ${oneline(e.message)}`);
  }
  if (r.validation.errors.length > sample.length) {
    drawMutedLine(doc, `…and ${r.validation.errors.length - sample.length} more`);
  }
}

function drawSelectedTaskBlock(doc: PDFKit.PDFDocument, r: PipelineResult): void {
  if (!(r.selectedTask && r.selectedFeature)) {
    drawMutedLine(doc, "No task was selected this run.");
    return;
  }
  const t = r.selectedTask;
  const f = r.selectedFeature;
  drawKeyValue(doc, "Task", `${t.id} — ${oneline(t.description)}`);
  drawKeyValue(doc, "Assignee", t.assignedTo);
  drawKeyValue(doc, "Estimate", `${t.estimatedHours} h`);
  drawKeyValue(doc, "Feature", `${f.id} — ${oneline(f.name)}`);
}

function drawFilesWrittenTable(doc: PDFKit.PDFDocument, r: PipelineResult): void {
  if (r.filesWritten.length === 0) {
    drawMutedLine(doc, "No files were written this run.");
    return;
  }
  const totalBytes = r.filesWritten.reduce((acc, f) => acc + f.bytes, 0);
  drawBodyLine(doc, `${r.filesWritten.length} file(s), ${totalBytes.toLocaleString()} bytes total.`);
  doc.moveDown(0.2);
  const cols = [
    { x: PAGE.margin.left, width: CONTENT_WIDTH - 80, align: "left" as const },
    { x: PAGE.margin.left + (CONTENT_WIDTH - 80), width: 80, align: "right" as const },
  ];
  drawTableHeader(doc, ["Path", "Bytes"], cols);
  for (let i = 0; i < r.filesWritten.length; i++) {
    const f = r.filesWritten[i];
    drawTableRow(
      doc,
      [f.declaredPath, f.bytes.toLocaleString()],
      cols,
      { striped: i % 2 === 1, cellFonts: ["code", undefined] },
    );
  }
  doc.moveDown(0.3);
}

// ---------- agent pages ----------

function drawAgentPage<T>(
  doc: PDFKit.PDFDocument,
  label: string,
  output: T | undefined,
  renderer: (doc: PDFKit.PDFDocument, output: T) => void,
): void {
  doc.addPage();
  drawAgentTitle(doc, label, output != null);
  if (output == null) {
    doc.font("Helvetica-Oblique").fontSize(11).fillColor(COLORS.textMuted);
    doc.text("Did not run.", PAGE.margin.left, doc.y, { width: CONTENT_WIDTH });
    return;
  }
  renderer(doc, output);
  doc.moveDown(0.6);
  drawJsonBlock(doc, `Full ${label} output (JSON)`, output);
}

function drawAgentTitle(doc: PDFKit.PDFDocument, label: string, ran: boolean): void {
  const y = doc.y;
  doc.save();
  doc.fillColor(ran ? COLORS.primaryDark : COLORS.textMuted);
  doc.rect(PAGE.margin.left, y, 4, 28).fill();
  doc.restore();
  doc.font("Helvetica-Bold").fontSize(22).fillColor(COLORS.text);
  doc.text(label, PAGE.margin.left + 14, y - 2, { width: CONTENT_WIDTH - 14 });
  doc.x = PAGE.margin.left;
  doc.moveDown(0.6);
}

function renderCEO(doc: PDFKit.PDFDocument, o: CEOOutput): void {
  drawKeyValue(doc, "Mission", oneline(o.mission) || "(empty)");
  drawSubheading(doc, "OKRs");
  if (o.okrs.length === 0) drawMutedLine(doc, "(none)");
  else for (const k of o.okrs) drawBulletLine(doc, oneline(k));
  drawSubheading(doc, "Priorities");
  if (o.priorities.length === 0) drawMutedLine(doc, "(none)");
  else for (const p of o.priorities) drawBulletLine(doc, oneline(p));
  drawSubheading(doc, "Delegation");
  drawKeyValue(doc, "CTO", oneline(o.delegation.cto) || "(empty)");
  drawKeyValue(doc, "CMO", oneline(o.delegation.cmo) || "(empty)");
  drawKeyValue(doc, "CFO", oneline(o.delegation.cfo) || "(empty)");
  drawKeyValue(doc, "CPO", oneline(o.delegation.cpo) || "(empty)");
}

function renderCTO(doc: PDFKit.PDFDocument, o: CTOOutput): void {
  drawSubheading(doc, "Architecture");
  drawKeyValue(doc, "Frontend", oneline(o.architecture.frontend));
  drawKeyValue(doc, "Backend", oneline(o.architecture.backend));
  drawKeyValue(doc, "Database", oneline(o.architecture.database));
  drawKeyValue(doc, "Infrastructure", oneline(o.architecture.infrastructure));

  drawSubheading(doc, `API contracts (${o.apiContracts.length})`);
  if (o.apiContracts.length === 0) drawMutedLine(doc, "(none)");
  else for (const a of o.apiContracts) drawBulletLine(doc, `${a.method} ${a.endpoint} — ${oneline(a.description)}`);

  drawSubheading(doc, `Database schema (${o.databaseSchema.length})`);
  if (o.databaseSchema.length === 0) drawMutedLine(doc, "(none)");
  else
    for (const t of o.databaseSchema) {
      drawBulletLine(doc, t.table, { bold: true });
      for (const f of t.fields) drawBulletLine(doc, oneline(f), { indent: 18 });
    }

  drawSubheading(doc, `Risks (${o.risks.length})`);
  if (o.risks.length === 0) drawMutedLine(doc, "(none)");
  else for (const r of o.risks) drawBulletLine(doc, oneline(r));
}

function renderEM(doc: PDFKit.PDFDocument, o: EMOutput): void {
  drawSubheading(doc, `Features (${o.features.length})`);
  if (o.features.length === 0) drawMutedLine(doc, "(none)");
  else for (const f of o.features) drawBulletLine(doc, `${f.id} (${f.priority}) — ${oneline(f.name)}`);

  drawSubheading(doc, `Tasks (${o.tasks.length})`);
  if (o.tasks.length === 0) drawMutedLine(doc, "(none)");
  else
    for (const t of o.tasks) {
      drawBulletLine(doc, `${t.id} -> ${t.featureId} · ${t.assignedTo} · ${t.estimatedHours}h - ${oneline(t.description)}`);
    }
}

function renderDeveloper(doc: PDFKit.PDFDocument, o: DeveloperOutput): void {
  drawKeyValue(doc, "Task", o.taskId);

  drawSubheading(doc, "Implementation plan");
  drawBodyLine(doc, oneline(o.implementationPlan), { italic: true });

  drawSubheading(doc, `Files produced (${o.files.length})`);
  if (o.files.length === 0) drawMutedLine(doc, "(none)");
  else for (const f of o.files) drawBulletLine(doc, `${f.path} (${f.content.length.toLocaleString()} bytes)`, { mono: true });

  drawSubheading(doc, `Tests (${o.tests.length})`);
  if (o.tests.length === 0) drawMutedLine(doc, "(none)");
  else for (const t of o.tests) drawBulletLine(doc, oneline(t.description));

  drawSubheading(doc, `Notes (${o.notes.length})`);
  if (o.notes.length === 0) drawMutedLine(doc, "(none)");
  else for (const n of o.notes) drawBulletLine(doc, oneline(n));
}

function renderQA(doc: PDFKit.PDFDocument, o: QAOutput): void {
  const passed = o.results.filter((r) => r.status === "pass").length;
  const failed = o.results.filter((r) => r.status === "fail").length;
  drawKeyValue(doc, "Decision", o.decision, { valueColor: qaDecisionColor(o.decision), bold: true });
  drawKeyValue(doc, "Test plan", `${o.testPlan.length} item(s)`);
  drawKeyValue(doc, "Results", `${passed} pass, ${failed} fail`);
  drawKeyValue(doc, "Bugs", String(o.bugs.length));

  drawSubheading(doc, `Bugs (${o.bugs.length})`);
  if (o.bugs.length === 0) drawMutedLine(doc, "(none)");
  else
    for (const b of o.bugs) {
      drawBulletLine(doc, oneline(b.description));
      drawBulletLine(doc, `expected: ${oneline(b.expected)}`, { indent: 18, muted: true });
      drawBulletLine(doc, `actual:   ${oneline(b.actual)}`, { indent: 18, muted: true });
    }
}

function renderSecurity(doc: PDFKit.PDFDocument, o: SecurityOutput): void {
  drawKeyValue(doc, "Decision", o.decision, { valueColor: securityDecisionColor(o.decision), bold: true });
  drawKeyValue(doc, "Summary", oneline(o.summary));
  drawKeyValue(doc, "Prompt-injection risk", oneline(o.promptInjectionRisk));

  drawSubheading(doc, `Vulnerabilities (${o.vulnerabilities.length})`);
  if (o.vulnerabilities.length === 0) drawMutedLine(doc, "(none)");
  else
    for (const v of o.vulnerabilities) {
      drawSeverityBullet(doc, v.severity, oneline(v.description));
      drawBulletLine(doc, `Recommendation: ${oneline(v.recommendation)}`, { indent: 18, muted: true });
    }

  drawSubheading(doc, `Required fixes (${o.requiredFixes.length})`);
  if (o.requiredFixes.length === 0) drawMutedLine(doc, "(none)");
  else for (const r of o.requiredFixes) drawBulletLine(doc, oneline(r));
}

// ---------- low-level drawing helpers ----------

function drawSubheading(doc: PDFKit.PDFDocument, label: string): void {
  ensureSpace(doc, 30);
  doc.moveDown(0.4);
  doc.font("Helvetica-Bold").fontSize(11).fillColor(COLORS.primaryDark);
  doc.text(label.toUpperCase(), PAGE.margin.left, doc.y, { characterSpacing: 1, width: CONTENT_WIDTH });
  doc.x = PAGE.margin.left;
  doc.moveDown(0.15);
}

function drawBodyLine(doc: PDFKit.PDFDocument, text: string, opts?: { italic?: boolean }): void {
  ensureSpace(doc, 22);
  doc.font(opts?.italic ? "Helvetica-Oblique" : "Helvetica").fontSize(11).fillColor(COLORS.text);
  doc.text(text, PAGE.margin.left, doc.y, { width: CONTENT_WIDTH, lineGap: 2 });
  doc.x = PAGE.margin.left;
}

function drawMutedLine(doc: PDFKit.PDFDocument, text: string): void {
  ensureSpace(doc, 18);
  doc.font("Helvetica-Oblique").fontSize(10).fillColor(COLORS.textMuted);
  doc.text(text, PAGE.margin.left, doc.y, { width: CONTENT_WIDTH });
  doc.x = PAGE.margin.left;
}

function drawBulletLine(
  doc: PDFKit.PDFDocument,
  text: string,
  opts?: { bold?: boolean; mono?: boolean; muted?: boolean; indent?: number },
): void {
  ensureSpace(doc, 18);
  const indent = opts?.indent ?? 4;
  const bulletX = PAGE.margin.left + indent;
  const textX = bulletX + 10;
  const y = doc.y;
  // Bullet character
  doc.font("Helvetica").fontSize(10).fillColor(opts?.muted ? COLORS.textMuted : COLORS.text);
  doc.text("•", bulletX, y, { width: 8 });
  // Text
  let font: string;
  if (opts?.mono) font = "Courier";
  else if (opts?.bold) font = "Helvetica-Bold";
  else font = "Helvetica";
  doc
    .font(font)
    .fontSize(opts?.mono ? 9.5 : 10.5)
    .fillColor(opts?.muted ? COLORS.textMuted : COLORS.text);
  doc.text(text, textX, y, { width: CONTENT_WIDTH - (textX - PAGE.margin.left), lineGap: 1 });
  doc.x = PAGE.margin.left;
}

function drawSeverityBullet(doc: PDFKit.PDFDocument, sev: SecurityOutput["vulnerabilities"][number]["severity"], text: string): void {
  ensureSpace(doc, 22);
  const color = severityColor(sev);
  const y = doc.y;
  // Severity pill
  doc.font("Helvetica-Bold").fontSize(8.5);
  const label = sev.toUpperCase();
  const labelWidth = doc.widthOfString(label) + 12;
  doc.save();
  doc.fillColor(color);
  drawRoundedRect(doc, PAGE.margin.left + 4, y + 1, labelWidth, 13, 3).fill();
  doc.restore();
  doc.fillColor(COLORS.white);
  doc.text(label, PAGE.margin.left + 4, y + 3, { width: labelWidth, align: "center" });
  // Description text
  doc.font("Helvetica").fontSize(10.5).fillColor(COLORS.text);
  doc.text(text, PAGE.margin.left + labelWidth + 14, y, {
    width: CONTENT_WIDTH - labelWidth - 18,
    lineGap: 1,
  });
  doc.x = PAGE.margin.left;
}

function drawKeyValue(
  doc: PDFKit.PDFDocument,
  key: string,
  value: string,
  opts?: { valueColor?: string; bold?: boolean },
): void {
  ensureSpace(doc, 20);
  const labelWidth = 110;
  const valueX = PAGE.margin.left + labelWidth + 8;
  const valueWidth = CONTENT_WIDTH - labelWidth - 8;
  const y = doc.y;
  doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.textMuted);
  doc.text(`${key}:`, PAGE.margin.left, y, { width: labelWidth });
  doc.font(opts?.bold ? "Helvetica-Bold" : "Helvetica").fontSize(11).fillColor(opts?.valueColor ?? COLORS.text);
  doc.text(value, valueX, y, { width: valueWidth, lineGap: 1 });
  doc.x = PAGE.margin.left;
}

function drawTableHeader(
  doc: PDFKit.PDFDocument,
  cells: ReadonlyArray<string>,
  cols: ReadonlyArray<{ x: number; width: number; align: "left" | "right" }>,
): void {
  ensureSpace(doc, 26);
  const y = doc.y;
  const totalWidth = cols.reduce((s, c) => s + c.width, 0);
  doc.save();
  doc.fillColor(COLORS.panelStrong);
  doc.rect(cols[0].x, y, totalWidth, 22).fill();
  doc.restore();
  doc.save();
  doc.strokeColor(COLORS.border).lineWidth(0.5);
  doc.moveTo(cols[0].x, y + 22).lineTo(cols[0].x + totalWidth, y + 22).stroke();
  doc.restore();
  doc.font("Helvetica-Bold").fontSize(9.5).fillColor(COLORS.primaryDark);
  for (let i = 0; i < cells.length; i++) {
    const col = cols[i];
    doc.text(cells[i], col.x + 6, y + 6, {
      width: col.width - 12,
      align: col.align,
      ellipsis: true,
    });
  }
  doc.y = y + 22;
  doc.x = PAGE.margin.left;
}

function drawTableRow(
  doc: PDFKit.PDFDocument,
  cells: ReadonlyArray<string>,
  cols: ReadonlyArray<{ x: number; width: number; align: "left" | "right" }>,
  opts?: {
    striped?: boolean;
    cellColors?: ReadonlyArray<string | undefined>;
    cellFonts?: ReadonlyArray<"code" | undefined>;
  },
): void {
  // Compute the natural row height by measuring the tallest cell.
  doc.font("Helvetica").fontSize(9.5);
  let rowHeight = 18;
  for (let i = 0; i < cells.length; i++) {
    const col = cols[i];
    const isCode = opts?.cellFonts?.[i] === "code";
    doc.font(isCode ? "Courier" : "Helvetica").fontSize(isCode ? 9 : 9.5);
    const h = doc.heightOfString(cells[i] || " ", { width: col.width - 12, align: col.align }) + 8;
    if (h > rowHeight) rowHeight = h;
  }
  ensureSpace(doc, rowHeight + 4);
  const y = doc.y;
  const totalWidth = cols.reduce((s, c) => s + c.width, 0);

  if (opts?.striped) {
    doc.save();
    doc.fillColor(COLORS.panel);
    doc.rect(cols[0].x, y, totalWidth, rowHeight).fill();
    doc.restore();
  }
  doc.save();
  doc.strokeColor(COLORS.border).lineWidth(0.5);
  doc.moveTo(cols[0].x, y + rowHeight).lineTo(cols[0].x + totalWidth, y + rowHeight).stroke();
  doc.restore();

  for (let i = 0; i < cells.length; i++) {
    const col = cols[i];
    const isCode = opts?.cellFonts?.[i] === "code";
    const color = opts?.cellColors?.[i] ?? COLORS.text;
    doc.font(isCode ? "Courier" : "Helvetica").fontSize(isCode ? 9 : 9.5).fillColor(color);
    doc.text(cells[i] || "", col.x + 6, y + 5, {
      width: col.width - 12,
      align: col.align,
      ellipsis: true,
      lineGap: 1,
    });
  }
  doc.y = y + rowHeight;
  doc.x = PAGE.margin.left;
}

function drawJsonBlock(doc: PDFKit.PDFDocument, label: string, body: unknown): void {
  drawSubheading(doc, label);
  // JSON is rendered through a built-in WinAnsi monospace, so it has the same
  // glyph-availability constraints as the prose text. Sanitise after stringify
  // so structure is preserved and only individual character glyphs are mapped.
  const json = pdfSafe(JSON.stringify(body, null, 2));
  const lineHeight = 11;
  const padding = 10;
  // Reserve a little space for the open of the box
  ensureSpace(doc, lineHeight * 4 + padding * 2);

  // We let PDFKit auto-paginate the text; the panel background is drawn under
  // the text block as a single rectangle on each page it spans. Easiest: draw
  // a single panel for the first segment, then a continuation panel on each
  // additional page using the page-add hook.
  const startPageIndex = currentPageIndex(doc);

  // Pre-render text into a temp buffer to know per-page slices? PDFKit doesn't
  // expose that. Instead: emit text + on every pageAdded during emission, draw
  // the panel from top-of-page down to where the text continues. This is tricky.
  //
  // Pragmatic alternative: just draw the JSON text in monospace with a faint
  // left rule rather than a full panel. Easier to reason about across pages.
  doc.font("Courier").fontSize(8).fillColor(COLORS.text);
  const startY = doc.y;
  const lineX = PAGE.margin.left;
  // Left guide bar
  doc.save();
  doc.fillColor(COLORS.code);
  doc.rect(lineX, startY, 3, Math.min(lineHeight * 6, PAGE_BOTTOM - startY)).fill();
  doc.restore();
  doc.text(json, PAGE.margin.left + 12, startY, {
    width: CONTENT_WIDTH - 12,
    lineGap: 1,
    indent: 0,
  });
  doc.x = PAGE.margin.left;
  // Mark the unused variable so the linter doesn't complain.
  void startPageIndex;
}

function drawRoundedRect(doc: PDFKit.PDFDocument, x: number, y: number, w: number, h: number, r: number): PDFKit.PDFDocument {
  const radius = Math.min(r, w / 2, h / 2);
  doc
    .moveTo(x + radius, y)
    .lineTo(x + w - radius, y)
    .quadraticCurveTo(x + w, y, x + w, y + radius)
    .lineTo(x + w, y + h - radius)
    .quadraticCurveTo(x + w, y + h, x + w - radius, y + h)
    .lineTo(x + radius, y + h)
    .quadraticCurveTo(x, y + h, x, y + h - radius)
    .lineTo(x, y + radius)
    .quadraticCurveTo(x, y, x + radius, y);
  return doc;
}

function ensureSpace(doc: PDFKit.PDFDocument, neededHeight: number): void {
  const available = PAGE_BOTTOM - doc.y;
  if (available < neededHeight) doc.addPage();
}

function currentPageIndex(doc: PDFKit.PDFDocument): number {
  const range = doc.bufferedPageRange();
  return range.start + range.count - 1;
}

// ---------- footers (called after all content is emitted) ----------

function addFootersToAllPages(doc: PDFKit.PDFDocument, footer: string, now: Date): void {
  const range = doc.bufferedPageRange();
  const total = range.count;
  for (let i = range.start; i < range.start + total; i++) {
    doc.switchToPage(i);
    const pageNum = i - range.start + 1;
    // Skip page 1 (the cover) so it stays clean — start numbering from page 2.
    if (pageNum === 1) continue;
    drawFooter(doc, footer, now, pageNum, total);
  }
}

function drawFooter(doc: PDFKit.PDFDocument, footer: string, now: Date, pageNum: number, total: number): void {
  const y = PAGE.height - PAGE.margin.bottom + 24;
  // Hairline rule
  doc.save();
  doc.strokeColor(COLORS.border).lineWidth(0.5);
  doc.moveTo(PAGE.margin.left, y - 8).lineTo(CONTENT_RIGHT, y - 8).stroke();
  doc.restore();

  const leftWidth = CONTENT_WIDTH * 0.6;
  doc.font("Helvetica").fontSize(8).fillColor(COLORS.textMuted);
  doc.text(footer, PAGE.margin.left, y, { width: leftWidth, align: "left" });
  doc.text(
    `Page ${pageNum} of ${total}  ·  ${now.toISOString()}`,
    PAGE.margin.left + leftWidth,
    y,
    { width: CONTENT_WIDTH - leftWidth, align: "right" },
  );
}

// ---------- visual-state lookups ----------

function decisionVisual(d: PipelineResult["decision"]): { color: string; label: string } {
  switch (d) {
    case "WROTE_FILES":
      return { color: COLORS.ok, label: "WROTE_FILES" };
    case "GATE_BLOCKED_QA":
    case "GATE_BLOCKED_SECURITY":
    case "VALIDATION_FAILED":
    case "NO_TASKS":
      return { color: COLORS.warn, label: d };
    case "RUNTIME_ERROR":
      return { color: COLORS.error, label: "RUNTIME_ERROR" };
  }
}

function stepStatusVisual(s: "ok" | "blocked" | "skipped"): { color: string; label: string } {
  switch (s) {
    case "ok":
      return { color: COLORS.ok, label: "ok" };
    case "blocked":
      return { color: COLORS.error, label: "blocked" };
    case "skipped":
      return { color: COLORS.textMuted, label: "skipped" };
  }
}

function qaDecisionColor(d: QAOutput["decision"]): string {
  if (d === "PASS") return COLORS.ok;
  if (d === "CONDITIONAL") return COLORS.warn;
  return COLORS.error;
}

function securityDecisionColor(d: SecurityOutput["decision"]): string {
  return d === "GO" ? COLORS.ok : COLORS.error;
}

function severityColor(s: SecurityOutput["vulnerabilities"][number]["severity"]): string {
  switch (s) {
    case "critical":
      return COLORS.sevCritical;
    case "high":
      return COLORS.sevHigh;
    case "medium":
      return COLORS.sevMedium;
    case "low":
      return COLORS.sevLow;
  }
}

function oneline(s: string): string {
  return pdfSafe((s ?? "").replace(/\s+/g, " ").trim());
}

// Drop-in sanitiser for text that has to render through PDFKit's built-in
// WinAnsi (CP1252) Type-1 fonts. Maps the most common "looks-like-WinAnsi
// but isn't" code points (arrows, ellipsis, emoji, severity blocks) to their
// ASCII fallbacks so the glyphs render correctly across PDF viewers and so
// that test extraction of the produced text is deterministic.
//
// Anything outside ASCII + the WinAnsi Latin-1 set + the explicit CP1252
// 0x80-0x9F extras is replaced with '?' rather than silently dropped — that
// way agent-supplied text that contains exotic characters surfaces visibly
// in the PDF rather than corrupting the surrounding glyphs.
const WIN_ANSI_REPLACEMENTS: Record<string, string> = {
  "\u2190": "<-",
  "\u2191": "^",
  "\u2192": "->",
  "\u2193": "v",
  "\u21D0": "<=",
  "\u21D1": "^^",
  "\u21D2": "=>",
  "\u21D3": "vv",
  "\u2026": "...",
  "\u2713": "v",
  "\u2714": "v",
  "\u2717": "x",
  "\u2718": "x",
  "\u2705": "[OK]",
  "\u274C": "[X]",
  "\u26A0": "[!]",
  "\uFE0F": "",
  "\u23F1": "",
  "\u2728": "",
  "\uD83D\uDFE5": "[critical]",
  "\uD83D\uDFE7": "[high]",
  "\uD83D\uDFE1": "[medium]",
  "\uD83D\uDFE2": "[low]",
};

const WIN_ANSI_EXTRAS = new Set<number>([
  0x20ac, 0x201a, 0x0192, 0x201e, 0x2020, 0x2021, 0x02c6, 0x2030, 0x0160,
  0x2039, 0x0152, 0x017d, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2013,
  0x2014, 0x02dc, 0x2122, 0x0161, 0x203a, 0x0153, 0x017e, 0x0178,
]);

export function pdfSafe(s: string | null | undefined): string {
  if (!s) return "";
  let out = "";
  for (let i = 0; i < s.length; ) {
    let ch: string;
    const code = s.charCodeAt(i);
    if (code >= 0xd800 && code <= 0xdbff && i + 1 < s.length) {
      // UTF-16 surrogate pair (e.g. emoji)
      ch = s.slice(i, i + 2);
      i += 2;
    } else {
      ch = s[i];
      i += 1;
    }
    if (Object.prototype.hasOwnProperty.call(WIN_ANSI_REPLACEMENTS, ch)) {
      out += WIN_ANSI_REPLACEMENTS[ch];
      continue;
    }
    const cp = ch.codePointAt(0)!;
    if (cp <= 0x7e) {
      out += ch;
      continue;
    }
    if (cp >= 0xa0 && cp <= 0xff) {
      out += ch;
      continue;
    }
    if (WIN_ANSI_EXTRAS.has(cp)) {
      out += ch;
      continue;
    }
    out += "?";
  }
  return out;
}
