"use client";

import { useState } from "react";

import type { GeneratedScreen } from "@/lib/platform/mcp/stitch.ts";
import type { Project } from "@/lib/platform/workflow/types.ts";
import { useProjectStore } from "@/stores/project-store.ts";
import { ApprovalFooter, ModalShell } from "./ModalShell";

interface DesignsModalProps {
  project: Project | null;
}

export function DesignsModal({ project }: DesignsModalProps) {
  const openModal = useProjectStore((s) => s.openModal);
  const setOpenModal = useProjectStore((s) => s.setOpenModal);
  const open = openModal === "designs" && !!project?.design;
  const [busy, setBusy] = useState(false);
  const [redesignFor, setRedesignFor] = useState<GeneratedScreen | null>(null);
  const [redesignPrompt, setRedesignPrompt] = useState("");
  const [showArchive, setShowArchive] = useState(false);

  const themeLocked = !!project?.design?.selectedTheme;

  async function approve(approved: boolean, comment?: string) {
    if (!project) return;
    setBusy(true);
    try {
      await fetch(`/api/project/${project.id}/approve`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ approved, comment }),
      });
      setOpenModal(null);
    } finally {
      setBusy(false);
    }
  }

  async function selectScreen(screen: GeneratedScreen) {
    if (!project) return;
    await fetch(`/api/project/${project.id}/design`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "select", screenId: screen.id }),
    });
  }

  async function submitRedesign() {
    if (!project || !redesignFor || !redesignPrompt.trim()) return;
    setBusy(true);
    try {
      await fetch(`/api/project/${project.id}/design`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "redesign",
          screenId: redesignFor.id,
          prompt: redesignPrompt.trim(),
        }),
      });
      setRedesignFor(null);
      setRedesignPrompt("");
    } finally {
      setBusy(false);
    }
  }

  if (!project?.design) return null;

  const screens = project.design.screens;
  const archived = project.design.archivedScreens ?? [];
  const selectedId = project.design.selectedScreenId;
  const selectedTheme = project.design.selectedTheme;

  const subtitle = themeLocked
    ? `Direction locked: ${selectedTheme}. The team is working against this single design; the other ${archived.length} ${archived.length === 1 ? "variant was" : "variants were"} archived. Click "Redesign" to iterate within the same theme.`
    : `Four candidate screens generated by the Designer through Stitch (Gemini 3.1 Pro). Each leans into a different stylistic direction — pick one and the other three are archived; the team will then work against the chosen design.`;

  return (
    <ModalShell
      open={open}
      title={
        themeLocked
          ? `Design — ${selectedTheme} direction`
          : "Design concepts — pick one direction"
      }
      subtitle={subtitle}
      size="xl"
      onClose={() => setOpenModal(null)}
      footer={
        project.stage === "design-approval" ? (
          <ApprovalFooter
            onApprove={(c) => approve(true, c)}
            onRequestChanges={(c) => approve(false, c)}
            busy={busy}
          />
        ) : (
          <div className="text-[11px] text-zinc-500">
            Read-only — design already approved.
          </div>
        )
      }
    >
      {project.design.revisions && project.design.revisions.length > 0 && (
        <section className="mb-4 rounded-xl border border-amber-400/30 bg-amber-500/[0.06] p-3">
          <h3 className="mb-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-amber-300">
            Revisions · {project.design.revisions.length} round
            {project.design.revisions.length === 1 ? "" : "s"} of feedback
          </h3>
          <ul className="space-y-3">
            {project.design.revisions.map((r, i) => (
              <li key={i} className="text-[12px]">
                <div className="text-amber-200">
                  Round {i + 1}:
                  <span className="ml-2 italic text-amber-100">
                    "{r.feedback}"
                  </span>
                </div>
                <ul className="mt-1 list-disc space-y-0.5 pl-5 text-zinc-300">
                  {r.changes.map((c, j) => (
                    <li key={j}>{c}</li>
                  ))}
                </ul>
              </li>
            ))}
          </ul>
        </section>
      )}

      <div
        className={`grid gap-4 ${themeLocked ? "grid-cols-1" : "grid-cols-2"}`}
      >
        {screens.map((s) => (
          <DesignCard
            key={s.id}
            screen={s}
            selected={selectedId === s.id}
            themeLocked={themeLocked}
            onSelect={() => selectScreen(s)}
            onRedesign={() => {
              setRedesignFor(s);
              setRedesignPrompt("");
            }}
          />
        ))}
      </div>

      {archived.length > 0 && (
        <section className="mt-5 rounded-xl border border-white/10 bg-floor-900/40 p-3">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-[11px] font-semibold uppercase tracking-[0.18em] text-zinc-400">
                Archived variants · {archived.length}
              </h3>
              <p className="mt-0.5 text-[11px] text-zinc-500">
                Not in use. Kept so the demo can show all directions the
                Designer generated.
              </p>
            </div>
            <button
              type="button"
              onClick={() => setShowArchive((v) => !v)}
              className="rounded-md border border-white/10 px-2 py-1 text-[10px] uppercase tracking-wider text-zinc-300 hover:bg-floor-800"
            >
              {showArchive ? "Hide" : "Show"}
            </button>
          </div>
          {showArchive && (
            <div className="mt-3 grid grid-cols-3 gap-3">
              {archived.map((s) => (
                <article
                  key={s.id}
                  className="overflow-hidden rounded-lg border border-white/5 bg-floor-950 opacity-60"
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={s.thumbnailUrl}
                    alt={s.title}
                    className="aspect-video w-full object-cover grayscale"
                  />
                  <div className="px-2 py-1.5">
                    <div className="text-[11px] font-medium text-zinc-300">
                      {s.title}
                    </div>
                    <a
                      href={s.figmaUrl}
                      target="_blank"
                      rel="noreferrer"
                      className="text-[9px] uppercase tracking-wider text-zinc-500 hover:text-zinc-300"
                    >
                      View archived ↗
                    </a>
                  </div>
                </article>
              ))}
            </div>
          )}
        </section>
      )}

      {themeLocked && screens.length === 1 && !redesignFor && (
        <div className="mt-4 rounded-md border border-emerald-400/20 bg-emerald-500/[0.04] px-3 py-2 text-[11px] text-emerald-200">
          {selectedTheme} direction confirmed. From here, every Stitch
          generation for this project (redesigns and any future screens) will
          stay in the {selectedTheme?.toLowerCase()} aesthetic.
        </div>
      )}

      {redesignFor && (
        <div className="mt-4 rounded-xl border border-cyan-400/30 bg-cyan-500/5 p-3">
          <div className="text-[11px] uppercase tracking-wider text-cyan-300">
            Redesign · {redesignFor.title}
          </div>
          <textarea
            value={redesignPrompt}
            onChange={(e) => setRedesignPrompt(e.target.value)}
            rows={2}
            placeholder="What should change? e.g. 'Make the CTA more prominent and switch the hero to a dark mode.'"
            className="mt-2 w-full resize-none rounded-md border border-white/10 bg-floor-950 px-2.5 py-1.5 text-[12px] text-zinc-100 placeholder:text-zinc-600 focus:border-cyan-500/50 focus:outline-none"
          />
          <div className="mt-2 flex justify-end gap-2">
            <button
              type="button"
              onClick={() => setRedesignFor(null)}
              className="rounded-md border border-white/10 px-2 py-1 text-[10px] uppercase tracking-wider text-zinc-300 hover:bg-floor-800"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={submitRedesign}
              disabled={!redesignPrompt.trim() || busy}
              className="rounded-md bg-cyan-500 px-3 py-1 text-[10px] font-semibold uppercase tracking-wider text-floor-950 hover:bg-cyan-400 disabled:opacity-40"
            >
              {busy ? "…" : "Send to Designer"}
            </button>
          </div>
        </div>
      )}
    </ModalShell>
  );
}

function DesignCard({
  screen,
  selected,
  themeLocked,
  onSelect,
  onRedesign,
}: {
  screen: GeneratedScreen;
  selected: boolean;
  themeLocked: boolean;
  onSelect: () => void;
  onRedesign: () => void;
}) {
  return (
    <article
      className={`overflow-hidden rounded-xl border-2 bg-floor-950 transition-colors ${
        selected
          ? "border-emerald-400"
          : "border-white/10 hover:border-cyan-400/40"
      }`}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={screen.thumbnailUrl}
        alt={screen.title}
        className="aspect-video w-full object-cover"
      />
      <div className="px-3 py-2">
        <div className="text-sm font-semibold text-zinc-100">
          {screen.title}
        </div>
        <div className="text-[11px] text-zinc-400">{screen.caption}</div>
        <div className="mt-2 flex items-center gap-2">
          {!themeLocked && (
            <button
              type="button"
              onClick={onSelect}
              className={`rounded-md px-2 py-1 text-[10px] font-semibold uppercase tracking-wider ${
                selected
                  ? "bg-emerald-500 text-floor-950"
                  : "border border-emerald-400/30 text-emerald-300 hover:bg-emerald-500/10"
              }`}
            >
              {selected ? "Selected" : "Pick this direction"}
            </button>
          )}
          {themeLocked && selected && (
            <span className="rounded-md bg-emerald-500/15 px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-300">
              ✓ Active design
            </span>
          )}
          <button
            type="button"
            onClick={onRedesign}
            className="rounded-md border border-cyan-400/30 px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-cyan-300 hover:bg-cyan-500/10"
          >
            Redesign
          </button>
          <a
            href={screen.figmaUrl}
            target="_blank"
            rel="noreferrer"
            title="Generated by Stitch (Gemini 3.1 Pro). Opens in Stitch's web app."
            className="ml-auto text-[10px] uppercase tracking-wider text-zinc-500 hover:text-zinc-300"
          >
            Open in Stitch ↗
          </a>
          <span
            className="text-[9px] uppercase tracking-wider text-zinc-600"
            title="Generated by Stitch (Gemini 3.1 Pro)"
          >
            Stitch · {screen.source}
          </span>
        </div>
      </div>
    </article>
  );
}
